# Generated by Django 5.2.7 on 2025-11-13 08:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_session_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('authenticated', 'Authenticated'), ('ready', 'Ready'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('last_state_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='queued', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('num_chats', models.IntegerField(default=0)),
                ('num_msgs', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapes', to='whatsapp.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'status'], name='whatsapp_sc_session_57a104_idx'), models.Index(fields=['status', 'started_at'], name='whatsapp_sc_status_b8d6a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpenedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_msg_id', models.CharField(db_index=True, max_length=512)),
                ('chat_id', models.CharField(db_index=True, max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('replied_msg_id', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('replied_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened', to='whatsapp.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'wa_msg_id'], name='whatsapp_op_session_990ea4_idx'), models.Index(fields=['session', 'chat_id', 'opened_at'], name='whatsapp_op_session_28ba5f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('replied_msg_id__isnull', True), ('replied_at__isnull', True)), models.Q(('replied_msg_id__isnull', False), ('replied_at__isnull', False)), _connector='OR'), name='opened_reply_fields_null_together')],
                'unique_together': {('session', 'wa_msg_id')},
            },
        ),
        migrations.CreateModel(
            name='UnreadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_msg_id', models.CharField(db_index=True, max_length=512)),
                ('chat_id', models.CharField(db_index=True, max_length=255)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, default='')),
                ('msg_ts', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unreads', to='whatsapp.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'wa_msg_id'], name='whatsapp_un_session_c74704_idx'), models.Index(fields=['session', 'chat_id', 'scraped_at'], name='whatsapp_un_session_7ca6da_idx')],
                'unique_together': {('session', 'wa_msg_id')},
            },
        ),
    ]
