# Generated by Django 5.2.7 on 2025-11-13 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='last_state_change',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
