# Generated by Django 5.2.8 on 2025-11-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_session_last_state_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapejob',
            name='session',
        ),
        migrations.DeleteModel(
            name='OpenedSession',
        ),
        migrations.DeleteModel(
            name='ScrapeJob',
        ),
    ]
