# Generated by Django 5.2.8 on 2025-11-15 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_remove_scrapejob_session_delete_openedsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=255)),
                ('wa_msg_id', models.CharField(db_index=True, max_length=512)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, default='')),
                ('from_me', models.BooleanField(db_index=True, default=False)),
                ('msg_ts', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='whatsapp.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'chat_id', 'msg_ts'], name='whatsapp_ch_session_944de2_idx')],
                'unique_together': {('session', 'wa_msg_id')},
            },
        ),
    ]
