# -*- coding: utf-8 -*-
"""from_json_to_jsonl_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhS0TKTmV4EFWJas7HCMQ5RLJz3It-ux
"""

import json, random, re
from pathlib import Path
from itertools import islice
import pandas as pd

random.seed(42)

SRC = Path("big_bang_theory.json")
OUT_TRAIN = Path("bbt_train.jsonl")
OUT_VAL   = Path("bbt_val.jsonl")
OUT_TEST  = Path("bbt_test.jsonl")

def clean_text(s: str) -> str:
    s = s.strip()
    s = re.sub(r"\s*\[[^\]]+\]\s*", " ", s)
    s = re.sub(r"\s*\([^\)]+\)\s*", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def format_context(turns):
    return "\n".join([f"<{spk}>: {txt}" for spk, txt in turns])

def write_jsonl(scenes, out_path, ctx_max_turns=6):
    cnt = 0
    with open(out_path, "w", encoding="utf-8") as w:
        for scene in scenes:
            turns = scene["turns"]
            for i in range(1, len(turns)):
                ctx = turns[max(0, i-ctx_max_turns):i]
                target_speaker, target_text = turns[i]
                if not target_text:
                    continue
                prompt = format_context(ctx) + f"\n<{target_speaker}>:"
                rec = {
                    "ep": scene["ep"],
                    "scene": scene["scene_idx"],
                    "turn_idx": i,
                    "target_speaker": target_speaker,
                    "prompt": prompt,
                    "target": target_text,
                }
                w.write(json.dumps(rec, ensure_ascii=False) + "\n")
                cnt += 1
    return cnt

def main():
    with open(SRC, "r", encoding="utf-8") as f:
        raw = json.load(f)

    scenes = []
    for ep_id, ep in raw.items():
        title = ep.get("Episode Title", "")
        script = ep.get("Script", [])
        for scene_idx, scene in enumerate(script):
            flat = []
            for item in scene:
                if isinstance(item, dict) and "Speaker" in item and "Text" in item:
                    spk = item["Speaker"].strip()
                    txt = clean_text(item["Text"])
                    if spk and txt:
                        flat.append((spk, txt))
            if len(flat) >= 4:
                scenes.append(dict(ep=ep_id, title=title, scene_idx=scene_idx, turns=flat))

    random.shuffle(scenes)
    n = len(scenes)
    n_train = int(0.8 * n)
    n_val = int(0.1 * n)

    train_s = scenes[:n_train]
    val_s = scenes[n_train:n_train+n_val]
    test_s = scenes[n_train+n_val:]

    print(f"Scenes: total={n}, train={len(train_s)}, val={len(val_s)}, test={len(test_s)}")

    c_train = write_jsonl(train_s, OUT_TRAIN)
    c_val = write_jsonl(val_s, OUT_VAL)
    c_test = write_jsonl(test_s, OUT_TEST)

    print(f"Samples: train={c_train}, val={c_val}, test={c_test}")
    print("Files written:")
    print(OUT_TRAIN, OUT_VAL, OUT_TEST)

if __name__ == "__main__":
    main()